CREATE TABLE posts1 (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    body VARCHAR(255) NOT NULL,
    due_date DATE NOT NULL,
    completion_date DATE,
    comments_count INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_posts_user_id
        FOREIGN KEY (user_id)
        REFERENCES users1(id)
        ON DELETE CASCADE ON UPDATE CASCADE
);